name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: jpplaero/ListSorter@main
        with:
          owner: jppalero
          repo: Test_Moc
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: test.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s